services:
  # Frontend built and served with Nginx
  nginx:
    build:
      content: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"  # Expose port 80 for HTTP traffic
    depends_on:
      - backend
    networks:
      - app-network

  # Express.js backend service
  backend:
    build:
      context: ./server  # Path to the backend directory
    volumes:
      - ./database:/usr/src/app/database  # Ensure SQLite persists on the host
    networks:
      - app-network
    environment:
      - NODE_ENV=production


networks:
  app-network:
    driver: bridge
