services:
  # React frontend service
  frontend:
    build:
      context: ./frontend  # Path to the frontend directory
    #ports:
    #  - "2000:80"  # Map host port 2000 to container port 80
    depends_on:
      - backend  # Ensure backend starts before frontend
    networks:
      - app-network

  # Express.js backend service
  backend:
    build:
      context: ./server  # Path to the backend directory
    #ports:
    #  - "8080:8080"  # Map host port 8080 to container port 8080
    volumes:
      - ./database:/usr/src/app/database  # Ensure SQLite persists on the host
    networks:
      - app-network
    environment:
      - NODE_ENV=production
  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"  # Expose port 80 for HTTP traffic
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro  # Use custom Nginx config
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
